INSERT INTO `event_manager`.`events`
(`event_name`,
`host`,
`start_time`,
`start_date`,
`end_time`,
`end_date`,
`address_01`,
`address_02`,
`city`,
`state`,
`zip_code`,
`created_at`,
`updated_at`)

VALUES

('Princeton University',
'Princeton University Visit',
CURRENT_TIME(),
DATE(NOW()),
CURRENT_TIME(),
DATE(NOW()),
'1746 University Way',
'Admissions Department',
'Princeton',
'NJ',
08544,
NOW(),
NOW()),

('University of California - LA',
'UC Los Angeles Tour',
CURRENT_TIME(),
DATE(NOW()),
CURRENT_TIME(),
DATE(NOW()),
'405 Hilgard Ave',
'Admissions Department',
'Los Angeles',
'CA',
90095,
NOW(),
NOW()),

('Harvard University',
'Harvard Prospect Visit',
CURRENT_TIME(),
DATE(NOW()),
CURRENT_TIME(),
DATE(NOW()),
'1636 University Way',
'Admissions Department',
'Cambridge',
'MA',
02138,
NOW(),
NOW()),

('University of Michigan - Ann Arbor',
'University Prospect Visit Day',
CURRENT_TIME(),
DATE(NOW()),
CURRENT_TIME(),
DATE(NOW()),
'500 S. State St.',
'Admissions Department',
'Ann Arbor',
'MI',
48109,
NOW(),
NOW()),

('Columbia University',
'Columbia University Visit',
CURRENT_TIME(),
DATE(NOW()),
CURRENT_TIME(),
DATE(NOW()),
'1754 University Way',
'Admissions Department',
'New York',
'NY',
10027,
NOW(),
NOW()),

('University of Florida',
'Gator Visit',
CURRENT_TIME(),
DATE(NOW()),
CURRENT_TIME(),
DATE(NOW()),
'201 Criser Hall',
'Admissions Department',
'Gainesville',
'FL',
32611,
NOW(),
NOW()),

('Stanford University',
'Stanford University Visit',
CURRENT_TIME(),
DATE(NOW()),
CURRENT_TIME(),
DATE(NOW()),
'1885 University Way',
'Admissions Department',
'Stanford',
'CA',
94305,
NOW(),
NOW()),

('University at Buffalo- SUNY',
'SUNY Tour of Buffalo',
CURRENT_TIME(),
DATE(NOW()),
CURRENT_TIME(),
DATE(NOW()),
'3435 Main Street',
'Admissions Department',
'Buffalo',
'NY',
14214,
NOW(),
NOW()),

('Yale University',
'Yale University Visit',
CURRENT_TIME(),
DATE(NOW()),
CURRENT_TIME(),
DATE(NOW()),
'1701 University Way',
'Admissions Department',
'New Haven',
'CT',
06520,
NOW(),
NOW()),

('Binghamton University - SUNY',
'SUNY Tour of Binghamton',
CURRENT_TIME(),
DATE(NOW()),
CURRENT_TIME(),
DATE(NOW()),
'PO Box 6000',
'Admissions Department',
'Binghamton',
'NY',
13902,
NOW(),
NOW()),

('John Hopkins',
'John Hopkins University Visit',
CURRENT_TIME(),
DATE(NOW()),
CURRENT_TIME(),
DATE(NOW()),
'1746 University Way',
'Admissions Department',
'Baltimore',
'MD',
14468,
NOW(),
NOW());